version: '3'
volumes:
  certs:
  vhost:
  html:
  db:
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
  lets-encrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: lets-encrypt
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
  onionboat:
    image: jheretic/onionboat
    container_name: onionboat
    ports: 
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  whoami:
    image: jwilder/whoami
    container_name: whoami
    environment:
      - VIRTUAL_HOST=who.elvery.net
      - LETSENCRYPT_HOST=who.elvery.net
      - LETSENCRYPT_EMAIL=simon@elvery.net
  initiate:
    image: abcnews/initiate
    container_name: initiate
    volumes:
      - db:/usr/db
    environment:
      - VIRTUAL_HOST=initiatecontact.com
      - LETSENCRYPT_HOST=initiatecontact.com
      - LETSENCRYPT_EMAIL=simon@elvery.net
      - DATABASE_PATH=/usr/db/data.sqlite
      - NODE_ENV=production
      - HIDDENSERVICE_NAME=initiate
    